########################################
## SHARED | deploykf-helpers
########################################
deployKF_helpers:
  deploykf_profiles:
    users_id_mapping: {"user-1":{"email":"mohamedfawzi.touati@mcn.gouv.qc.ca","id":"user-1"},"user-2":{"email":"pierre.jiji@mcn.gouv.qc.ca","id":"user-2"},"user-3":{"email":"kami.rousseau@mcn.gouv.qc.ca","id":"user-3"}}
    profiles_users_access_mapping: {"team-1":{"user-1":{"notebooksAccess":true,"role":"edit"},"user-2":{"notebooksAccess":true,"role":"edit"}},"team-1-prod":{"user-1":{"notebooksAccess":false,"role":"view"},"user-2":{"notebooksAccess":false,"role":"view"}},"team-fawzi":{"user-1":{"notebooksAccess":true,"role":"edit"},"user-2":{"notebooksAccess":true,"role":"edit"}}}
    users_profiles_access_mapping: {"user-1":{"team-1":{"notebooksAccess":true,"role":"edit"},"team-1-prod":{"notebooksAccess":false,"role":"view"},"team-fawzi":{"notebooksAccess":true,"role":"edit"}},"user-2":{"team-1":{"notebooksAccess":true,"role":"edit"},"team-1-prod":{"notebooksAccess":false,"role":"view"},"team-fawzi":{"notebooksAccess":true,"role":"edit"}}}

  kubeflow:
    pipelines:
      object_store:
        profile:
          cloned_secret_name: "cloned--pipelines-object-store-auth"

########################################
## SHARED | deploykf
########################################
deployKF:
  extraManifests:

  clusterDomain: cluster.local

  argoWorkflows:
    enabled: true
    namespace: "kubeflow-argo-workflows"

  kubeflow:
    useridHeader: kubeflow-userid

    pipelines:
      enabled: true
      pipelineUI:
        namespace: kubeflow
        serviceAccount: ml-pipeline-ui

  gateway:
    namespace: "deploykf-istio-gateway"
    serviceAccount: "deploykf-gateway"
    emailToLowercase: false


########################################
## CONFIGS | profiles
########################################

## profile defaults
##
profileDefaults:

  ## a common prefix to add to all profile names
  ##
  profileNamePrefix: ""

  ## the default email to set as the owner of profiles
  ##
  ownerEmail: "admin@example.com"

  ## the default access for members of profiles, when not explicitly specified
  ##
  memberAccess:

    ## the Kubernetes RBAC role to bind to users in the profile namespace
    ##  - "edit": binds "ClusterRole/kubeflow-edit" (can view/create/delete resources)
    ##  - "view": binds "ClusterRole/kubeflow-view" (cam view resources)
    ##
    role: "view"

    ## if the user can ~connect~ to kubeflow notebooks in the profile
    ##
    notebooksAccess: false

  ## the default list of plugins for profiles, when not explicitly specified
  ##
  plugins: [{"kind":"AwsIamForServiceAccount","spec":{"AnnotateOnly":true,"awsIamRole":"arn:aws:iam::131485263174:role/kubeflow-pipelines-backend"}}]

  ## the default resource quota for profiles, when not explicitly specified
  ##  - spec for ResourceQuotaSpec:
  ##    https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#resourcequotaspec-v1-core
  ##
  resourceQuotaSpec: {}

## user entities
##  - a list of users that can be referenced when defining profile members
##
users: [{"email":"mohamedfawzi.touati@mcn.gouv.qc.ca","id":"user-1"},{"email":"pierre.jiji@mcn.gouv.qc.ca","id":"user-2"},{"email":"kami.rousseau@mcn.gouv.qc.ca","id":"user-3"}]

## group entities
##  - a list of groups that can be referenced when defining profile members
##
groups: [{"id":"team-1--admins","users":["user-1","user-2"]},{"id":"team-1--users","users":["user-1","user-2","user-3"]}]

## profile definitions
##  - a list of profile definitions to be generated
##
profiles: [{"members":[{"access":{"notebooksAccess":true,"role":"edit"},"group":"team-1--admins"}],"name":"team-fawzi","plugins":[{"kind":"AwsIamForServiceAccount","spec":{"AnnotateOnly":true,"awsIamRole":"arn:aws:iam::131485263174:role/team-fawzi-role"}}]},{"members":[{"access":{"notebooksAccess":true,"role":"edit"},"group":"team-1--admins"}],"name":"team-1","plugins":[{"kind":"AwsIamForServiceAccount","spec":{"AnnotateOnly":true,"awsIamRole":"arn:aws:iam::131485263174:role/team-1-role"}}]},{"members":[{"access":{"notebooksAccess":false,"role":"view"},"group":"team-1--admins"}],"name":"team-1-prod"}]
